---
- name: install numpy
  pip: name=numpy state=present

- name: install libopenblas-dev
  apt: name=libopenblas-dev state=present

- name: install liblapack-dev
  apt: name=liblapack-dev state=present

- name: install gfortran
  apt: name=gfortran state=present

  # from scipy.misc import factorial
  # causes error: ImportError: cannot import name 'factorial'
  # https://stackoverflow.com/questions/56283294/importerror-cannot-import-name-factorial
- name: install scipy
  pip: name=scipy==1.2 state=present

- name: install sklearn
  pip: name=sklearn state=present

- name: install pandas
  pip: name=pandas state=present

- name: install jupyter notebook
  pip: name=jupyter state=present

- name: install jupyter notebook extensions
  pip: name=jupyter_contrib_nbextensions state=present

- name: install jupytext
  pip: name=jupytext state=present

- name: install pydot3
  pip: name=pydot3 state=present

- name: install watermark
  pip: name=watermark state=present

- name: Install libjpeg8-dev for pillow
  apt: pkg=libjpeg8-dev state=present

- name: install Pillow
  pip: name=pillow state=present
